# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
  # Set options, as documented at https://datatables.net/reference/option/
  options:
    lengthMenu: [ 10, 20, 50, 100 ]
    pageLength: 20
    dom: "<'row' <'col-sm-12' tr>><'row' <'col-sm-6'l><'col-sm-6 text-right'pi>>"
  template: 'components/datatable.html.twig'

  template_parameters:
    # Example classes to integrate nicely with Bootstrap 3.x
    className: 'table table-striped table-bordered table-hover data-table'
  #    columnFilter: 'thead'

  # You can for example override this to "tables" to keep the translation domains separated nicely
  translation_domain: 'messages'
