# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
  security_tokens:
    - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
    - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

  email:
    digits: 6
    enabled: true
    sender_email: no-reply@example.com
    sender_name: ENSET-M School  # Optional
    template: security/two_factor.html.twig

  trusted_device:
    enabled: true                 # If the trusted device feature should be enabled
    lifetime: 5184000              # Lifetime of the trusted device token
    extend_lifetime: false         # Automatically extend lifetime of the trusted cookie on re-login
    cookie_name: trusted_device    # Name of the trusted device cookie
    cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
    cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax" or "strict"
    cookie_domain: "dwm.wip"  # Domain to use when setting the cookie, fallback to the request domain if not set
    cookie_path: "/"